-- MySQL Script generated by MySQL Workbench
-- Mon Mar 20 17:04:53 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nome_usuario` VARCHAR(255) NULL,
  `nome_completo` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `nivel` INT(2) NOT NULL,
  `telefone` VARCHAR(15) NOT NULL,
  `id_reserva` INT(11) NOT NULL,
  `status` TINYINT NOT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `idusuarios_UNIQUE` (`id_usuario` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`reservas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`reservas` (
  `id_reserva` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT(11) NOT NULL,
  `reservascol` VARCHAR(45) NOT NULL,
  `checkin` DATETIME NOT NULL,
  `checkout` DATETIME NOT NULL,
  `id_acomodacao` INT(11) NOT NULL,
  `informacoes` VARCHAR(255) NOT NULL,
  `quantidade_pessoas` INT(11) NOT NULL,
  `id_servicos` INT NOT NULL,
  `id_consumo` INT NOT NULL,
  `usuarios_id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_reserva`, `usuarios_id_usuario`),
  INDEX `fk_reservas_usuarios_idx` (`usuarios_id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_reservas_usuarios`
    FOREIGN KEY (`usuarios_id_usuario`)
    REFERENCES `mydb`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`acomodacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`acomodacao` (
  `id_acomodacao` INT NOT NULL AUTO_INCREMENT,
  `id_acomodacao_tipo` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  `status` TINYINT NOT NULL,
  `reservas_id_reserva` INT NOT NULL,
  `reservas_usuarios_id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_acomodacao`),
  INDEX `fk_acomodacao_reservas1_idx` (`reservas_id_reserva` ASC, `reservas_usuarios_id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_acomodacao_reservas1`
    FOREIGN KEY (`reservas_id_reserva` , `reservas_usuarios_id_usuario`)
    REFERENCES `mydb`.`reservas` (`id_reserva` , `usuarios_id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`servicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`servicos` (
  `id_servico` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `valor` DOUBLE NULL,
  PRIMARY KEY (`id_servico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`acomodacao_tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`acomodacao_tipo` (
  `id_acomodacao_tipo` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  `valor` DOUBLE NOT NULL,
  `acomodacao_id_acomodacao` INT NOT NULL,
  PRIMARY KEY (`id_acomodacao_tipo`),
  INDEX `fk_acomodacao_tipo_acomodacao1_idx` (`acomodacao_id_acomodacao` ASC) VISIBLE,
  CONSTRAINT `fk_acomodacao_tipo_acomodacao1`
    FOREIGN KEY (`acomodacao_id_acomodacao`)
    REFERENCES `mydb`.`acomodacao` (`id_acomodacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`consumos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`consumos` (
  `id_consumo` INT NOT NULL AUTO_INCREMENT,
  `pdv` TINYINT NOT NULL,
  `id_produto` INT NOT NULL,
  `id_reserva` INT NOT NULL,
  PRIMARY KEY (`id_consumo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`produtos` (
  `id_produto` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `valor` DOUBLE NULL,
  PRIMARY KEY (`id_produto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`reservas_has_servicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`reservas_has_servicos` (
  `reservas_id_reserva` INT NOT NULL,
  `reservas_usuarios_id_usuario` INT NOT NULL,
  `servicos_id_servico` INT NOT NULL,
  PRIMARY KEY (`reservas_id_reserva`, `reservas_usuarios_id_usuario`, `servicos_id_servico`),
  INDEX `fk_reservas_has_servicos_servicos1_idx` (`servicos_id_servico` ASC) VISIBLE,
  INDEX `fk_reservas_has_servicos_reservas1_idx` (`reservas_id_reserva` ASC, `reservas_usuarios_id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_reservas_has_servicos_reservas1`
    FOREIGN KEY (`reservas_id_reserva` , `reservas_usuarios_id_usuario`)
    REFERENCES `mydb`.`reservas` (`id_reserva` , `usuarios_id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reservas_has_servicos_servicos1`
    FOREIGN KEY (`servicos_id_servico`)
    REFERENCES `mydb`.`servicos` (`id_servico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`consumos_has_reservas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`consumos_has_reservas` (
  `consumos_id_consumo` INT NOT NULL,
  `reservas_id_reserva` INT NOT NULL,
  `reservas_usuarios_id_usuario` INT NOT NULL,
  PRIMARY KEY (`consumos_id_consumo`, `reservas_id_reserva`, `reservas_usuarios_id_usuario`),
  INDEX `fk_consumos_has_reservas_reservas1_idx` (`reservas_id_reserva` ASC, `reservas_usuarios_id_usuario` ASC) VISIBLE,
  INDEX `fk_consumos_has_reservas_consumos1_idx` (`consumos_id_consumo` ASC) VISIBLE,
  CONSTRAINT `fk_consumos_has_reservas_consumos1`
    FOREIGN KEY (`consumos_id_consumo`)
    REFERENCES `mydb`.`consumos` (`id_consumo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_consumos_has_reservas_reservas1`
    FOREIGN KEY (`reservas_id_reserva` , `reservas_usuarios_id_usuario`)
    REFERENCES `mydb`.`reservas` (`id_reserva` , `usuarios_id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`produtos_has_consumos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`produtos_has_consumos` (
  `produtos_id_produto` INT NOT NULL,
  `consumos_id_consumo` INT NOT NULL,
  PRIMARY KEY (`produtos_id_produto`, `consumos_id_consumo`),
  INDEX `fk_produtos_has_consumos_consumos1_idx` (`consumos_id_consumo` ASC) VISIBLE,
  INDEX `fk_produtos_has_consumos_produtos1_idx` (`produtos_id_produto` ASC) VISIBLE,
  CONSTRAINT `fk_produtos_has_consumos_produtos1`
    FOREIGN KEY (`produtos_id_produto`)
    REFERENCES `mydb`.`produtos` (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produtos_has_consumos_consumos1`
    FOREIGN KEY (`consumos_id_consumo`)
    REFERENCES `mydb`.`consumos` (`id_consumo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
